export const usersDemoData = [
  {
    name: "Travis Herron",
    email: "travis@gmail.com ",
    phone: "+1 863 567-6765",
    subscription: "paid",
    subscriptionsDate: "11-12-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "Arjo Neel",
    email: "neel@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "unpaid",
    subscriptionsDate: "27-06-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "Salman H Saikote",
    email: "salman@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "paid",
    subscriptionsDate: "19-05-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "Sadit Hasan",
    email: "sadit@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "unpaid",
    subscriptionsDate: "1-02-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "AR Sahak",
    email: "sahak@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "paid",
    subscriptionsDate: "12-08-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "NJ Milon",
    email: "milon@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "paid",
    subscriptionsDate: "12-07-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "Raihan Ali",
    email: "raihan@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "unpaid",
    subscriptionsDate: "12-12-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "Abu Kawsar",
    email: "kawsar@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "paid",
    subscriptionsDate: "12-12-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "Rahat Rahman",
    email: "rahat@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "unpaid",
    subscriptionsDate: "12-12-2024",
    address: "Dhaka, Bangladesh",
  },
  {
    name: "Jannat Fardouse",
    email: "jannat@gmail.com",
    phone: "+1 863 567-6765",
    subscription: "paid",
    subscriptionsDate: "12-12-2024",
    address: "Dhaka, Bangladesh",
  },
];
